In [4]:
# Torch dataloader indexing

from torch.utils.data import DataLoader

data_itr = DataLoader([1,2,3,4,5,6,7,8,9,10], batch_size=2, shuffle=False, drop_last=True).__iter__()

for i in range(4):
    # Check if iterator is exhausted
    try:
        print(next(data_itr))
    except StopIteration:
        print(f'Iteration {i} is the last iteration')
        break

tensor([1, 2])
tensor([3, 4])
tensor([5, 6])
tensor([7, 8])
